import type { MaterialSpec, StylePack } from '../scene/schemas';

const paint = (name: string, color: string, tags: string[]): MaterialSpec => ({
  name,
  category: 'paint',
  baseColor: color,
  pbr: { roughness: 0.93, metallic: 0, repeatScale: 1000 },
  styleTags: tags,
});

/**
 * Phase 1 ships these five; the full set of twelve arrives in Phase 5.
 * Packs reference asset-cache texture keys; everything degrades to flat
 * PBR colors when textures aren't downloaded.
 */
export const STYLE_PACKS: StylePack[] = [
  {
    id: 'indian-modern',
    name: 'Indian Modern',
    description: 'Clean contemporary lines with warm Indian materiality — teak, brass, ivory marble.',
    palette: ['#f4efe6', '#8a5a34', '#a98343', '#1f3a36', '#b46a4a'],
    wallPaint: paint('Ivory Silk', '#f1ece1', ['indian-modern']),
    accentWall: paint('Deep Teal Accent', '#1f3a36', ['indian-modern']),
    floorMaterial: {
      name: 'Ivory Marble',
      category: 'marble',
      baseColor: '#e9e4da',
      pbr: { roughness: 0.18, metallic: 0, textureSetRef: 'marble_ivory', repeatScale: 1200 },
      styleTags: ['indian-modern'],
    },
    wetFloorMaterial: {
      name: 'Grey Porcelain',
      category: 'ceramicTile',
      baseColor: '#b9b9b4',
      pbr: { roughness: 0.3, metallic: 0, textureSetRef: 'tiles_porcelain', repeatScale: 600 },
      styleTags: ['indian-modern'],
    },
    furnitureFamilies: ['teak-frame', 'brass-detail', 'linen-upholstery'],
    lightingNotes: 'Warm 2700K, brass pendant over dining, recessed wash on accent wall.',
    textileNotes: 'Raw silk cushions, handloom cotton drapes in ivory and teal.',
    decorElements: ['brass urli', 'block-print art', 'potted plants'],
    budgetTier: 'moderate',
    reasoning:
      'Marble + teak + brass reads premium-Indian without ornamentation; teal accent anchors the living wall.',
    roomOverrides: {
      kitchen: {
        floorMaterial: {
          name: 'Grey Porcelain',
          category: 'ceramicTile',
          baseColor: '#b9b9b4',
          pbr: { roughness: 0.3, metallic: 0, textureSetRef: 'tiles_porcelain', repeatScale: 600 },
          styleTags: ['indian-modern'],
        },
      },
    },
  },
  {
    id: 'rajasthani-heritage',
    name: 'Rajasthani Heritage',
    description: 'Jaipur havelis — lime plaster, sandstone, jharokha arches, deep jewel textiles.',
    palette: ['#ddd0b8', '#b3614a', '#1f5448', '#a98343', '#7a2e2e'],
    wallPaint: {
      name: 'Sand Limewash',
      category: 'limewash',
      baseColor: '#ddd0b8',
      pbr: { roughness: 0.97, metallic: 0, textureSetRef: 'plaster_rough', repeatScale: 1500 },
      styleTags: ['rajasthani-heritage'],
    },
    accentWall: paint('Madder Red Accent', '#7a2e2e', ['rajasthani-heritage']),
    floorMaterial: {
      name: 'Sandstone',
      category: 'stone',
      baseColor: '#c8b394',
      pbr: { roughness: 0.75, metallic: 0, textureSetRef: 'stone_sandstone', repeatScale: 900 },
      styleTags: ['rajasthani-heritage'],
    },
    furnitureFamilies: ['carved-wood', 'inlay-work', 'jewel-velvet'],
    lightingNotes: 'Pierced-metal lanterns, warm pools of light, candle-scale at night.',
    textileNotes: 'Bandhani and leheriya silks, emerald and madder velvets, kilim dhurries.',
    decorElements: ['jaali screen', 'miniature paintings', 'blue pottery'],
    budgetTier: 'premium',
    reasoning: 'Limewash + sandstone is the authentic haveli base; jewel textiles carry the drama.',
  },
  {
    id: 'fusion-japandi',
    name: 'Fusion Japandi',
    description: 'Japanese restraint meets Indian craft — oak, cane, beige walls, linen.',
    palette: ['#e7dcc8', '#b08a5e', '#c9a86a', '#5b5a52', '#cfc4ae'],
    wallPaint: paint('Soft Beige', '#e7dcc8', ['fusion-japandi']),
    floorMaterial: {
      name: 'Warm Oak',
      category: 'wood',
      baseColor: '#b08a5e',
      pbr: { roughness: 0.55, metallic: 0, textureSetRef: 'wood_floor_oak', repeatScale: 1400 },
      styleTags: ['fusion-japandi'],
    },
    furnitureFamilies: ['low-profile-oak', 'cane-accent', 'linen-upholstery'],
    lightingNotes: 'Diffuse paper-shade pendants, 3000K, nothing glossy.',
    textileNotes: 'Undyed linen, khadi throws, single indigo accent.',
    decorElements: ['cane screen', 'ikebana-style stems', 'stoneware'],
    budgetTier: 'moderate',
    reasoning: "Cane is the bridge: Japandi's negative space with Indian craft warmth.",
  },
  {
    id: 'warm-minimal',
    name: 'Warm Minimal',
    description: 'Quiet, decluttered, sunlit — warm whites, pale oak, soft textures.',
    palette: ['#f4efe6', '#d9cdb8', '#b08a5e', '#9c9587', '#6e6759'],
    wallPaint: paint('Warm White', '#f4efe6', ['warm-minimal']),
    floorMaterial: {
      name: 'Pale Oak',
      category: 'wood',
      baseColor: '#c39e72',
      pbr: { roughness: 0.6, metallic: 0, textureSetRef: 'wood_floor_oak', repeatScale: 1400 },
      styleTags: ['warm-minimal'],
    },
    furnitureFamilies: ['soft-curves', 'boucle', 'light-wood'],
    lightingNotes: 'Indirect coves, one sculptural floor lamp per room.',
    textileNotes: 'Boucle, washed cotton, tonal layering — no pattern.',
    decorElements: ['single large artwork', 'ceramic vessels'],
    budgetTier: 'budget',
    reasoning: 'Fewest moves, maximum calm; works with existing furniture silhouettes.',
  },
  {
    id: 'contemporary-luxury',
    name: 'Contemporary Luxury',
    description: 'Hotel-suite polish — walnut, marble, bronze, layered lighting.',
    palette: ['#e9e4da', '#6b4a32', '#2d2c2a', '#a98343', '#44423d'],
    wallPaint: paint('Greige Silk', '#e3ddd2', ['contemporary-luxury']),
    accentWall: {
      name: 'Walnut Panelling',
      category: 'wood',
      baseColor: '#6b4a32',
      pbr: { roughness: 0.4, metallic: 0, textureSetRef: 'wood_floor_walnut', repeatScale: 900 },
      styleTags: ['contemporary-luxury'],
    },
    floorMaterial: {
      name: 'Ivory Marble',
      category: 'marble',
      baseColor: '#e9e4da',
      pbr: { roughness: 0.15, metallic: 0, textureSetRef: 'marble_ivory', repeatScale: 1400 },
      styleTags: ['contemporary-luxury'],
    },
    furnitureFamilies: ['walnut-veneer', 'bronze-detail', 'velvet'],
    lightingNotes: 'Layered: cove + picture lights + dimmable pendants, 2700K.',
    textileNotes: 'Velvet, high-thread cotton, silk-wool rugs.',
    decorElements: ['smoked-glass decor', 'sculptural lighting', 'large mirrors'],
    budgetTier: 'premium',
    reasoning: 'Walnut-against-marble contrast plus layered light is the suite formula.',
  },
  {
    id: 'coastal-kerala',
    name: 'Coastal Kerala',
    description:
      'Backwater calm — lime-white walls, red-oxide floors, teak and cane, breezy whites and sea-greens.',
    palette: ['#f3efe4', '#9c4a2f', '#3f6f63', '#caa86a', '#2e4a45'],
    wallPaint: {
      name: 'Lime White',
      category: 'limewash',
      baseColor: '#f3efe4',
      pbr: { roughness: 0.96, metallic: 0, textureSetRef: 'plaster_smooth', repeatScale: 1500 },
      styleTags: ['coastal-kerala'],
    },
    accentWall: {
      name: 'Backwater Green',
      category: 'paint',
      baseColor: '#3f6f63',
      pbr: { roughness: 0.92, metallic: 0, repeatScale: 1000 },
      styleTags: ['coastal-kerala'],
    },
    floorMaterial: {
      name: 'Red Oxide',
      category: 'concrete',
      baseColor: '#9c4a2f',
      pbr: { roughness: 0.45, metallic: 0, textureSetRef: 'concrete_oxide', repeatScale: 1600 },
      styleTags: ['coastal-kerala'],
    },
    wetFloorMaterial: {
      name: 'Athangudi Wet Tile',
      category: 'ceramicTile',
      baseColor: '#b88a52',
      pbr: { roughness: 0.35, metallic: 0, textureSetRef: 'tiles_athangudi', repeatScale: 600 },
      styleTags: ['coastal-kerala'],
    },
    furnitureFamilies: ['teak-frame', 'cane-weave', 'rattan-accent'],
    lightingNotes: 'Warm 2700K, woven-shade pendants, generous daylight through louvred shutters.',
    textileNotes: 'Crisp white cotton, kasavu-bordered drapes, indigo block-print cushions.',
    decorElements: ['brass uruli', 'coconut-shell vessels', 'potted palms', 'cane lampshades'],
    budgetTier: 'moderate',
    reasoning:
      'Red-oxide-against-lime-white is the signature Kerala tropical base; teak and cane keep it breezy and humid-climate honest.',
    roomOverrides: {
      bathroom: {
        floorMaterial: {
          name: 'Athangudi Wet Tile',
          category: 'ceramicTile',
          baseColor: '#b88a52',
          pbr: { roughness: 0.35, metallic: 0, textureSetRef: 'tiles_athangudi', repeatScale: 600 },
          styleTags: ['coastal-kerala'],
        },
      },
    },
  },
  {
    id: 'goan-portuguese',
    name: 'Goan Portuguese',
    description:
      'Indo-Portuguese villa — sunwashed ochre and indigo, azulejo tiles, terracotta, mother-of-pearl light.',
    palette: ['#f1e3c6', '#2f5d8a', '#b9472f', '#d9a441', '#7a4a2b'],
    wallPaint: {
      name: 'Ochre Wash',
      category: 'limewash',
      baseColor: '#f1e3c6',
      pbr: { roughness: 0.95, metallic: 0, textureSetRef: 'plaster_rough', repeatScale: 1500 },
      styleTags: ['goan-portuguese'],
    },
    accentWall: {
      name: 'Azulejo Indigo',
      category: 'ceramicTile',
      baseColor: '#2f5d8a',
      pbr: { roughness: 0.22, metallic: 0, textureSetRef: 'tiles_azulejo', repeatScale: 450 },
      styleTags: ['goan-portuguese'],
    },
    floorMaterial: {
      name: 'Terracotta Tile',
      category: 'terracotta',
      baseColor: '#b9472f',
      pbr: { roughness: 0.55, metallic: 0, textureSetRef: 'terracotta_tile', repeatScale: 700 },
      styleTags: ['goan-portuguese'],
    },
    wetFloorMaterial: {
      name: 'Patterned Cement Tile',
      category: 'ceramicTile',
      baseColor: '#d9c8a8',
      pbr: { roughness: 0.3, metallic: 0, textureSetRef: 'tiles_cement_pattern', repeatScale: 500 },
      styleTags: ['goan-portuguese'],
    },
    furnitureFamilies: ['rosewood-carved', 'rattan-back', 'wrought-iron'],
    lightingNotes: 'Warm 2700K, mother-of-pearl shell pendants, wrought-iron sconces by the veranda.',
    textileNotes: 'Crochet lace, striped cotton, indigo-and-white prints, linen drapes.',
    decorElements: ['azulejo panels', 'oyster-shell window inserts', 'ceramic roosters', 'iron lanterns'],
    budgetTier: 'moderate',
    reasoning:
      'Terracotta floors with indigo azulejo accents and ochre walls recreate the Indo-Portuguese villa palette without pastiche.',
    roomOverrides: {
      kitchen: {
        floorMaterial: {
          name: 'Patterned Cement Tile',
          category: 'ceramicTile',
          baseColor: '#d9c8a8',
          pbr: { roughness: 0.3, metallic: 0, textureSetRef: 'tiles_cement_pattern', repeatScale: 500 },
          styleTags: ['goan-portuguese'],
        },
      },
    },
  },
  {
    id: 'chettinad-heritage',
    name: 'Chettinad Heritage',
    description:
      'Tamil mansion grandeur — Athangudi tiles, Burma teak, eggplant and turmeric, Chettiar craft.',
    palette: ['#efe6d0', '#5a2a3a', '#b88a2a', '#2f4538', '#8a3b22'],
    wallPaint: {
      name: 'Aged Ivory Plaster',
      category: 'texturedPlaster',
      baseColor: '#efe6d0',
      pbr: { roughness: 0.9, metallic: 0, textureSetRef: 'plaster_rough', repeatScale: 1500 },
      styleTags: ['chettinad-heritage'],
    },
    accentWall: {
      name: 'Eggplant Lacquer',
      category: 'paint',
      baseColor: '#5a2a3a',
      pbr: { roughness: 0.45, metallic: 0, repeatScale: 1000 },
      styleTags: ['chettinad-heritage'],
    },
    floorMaterial: {
      name: 'Athangudi Tile',
      category: 'ceramicTile',
      baseColor: '#b88a2a',
      pbr: { roughness: 0.28, metallic: 0, textureSetRef: 'tiles_athangudi', repeatScale: 550 },
      styleTags: ['chettinad-heritage'],
    },
    wetFloorMaterial: {
      name: 'Kadappa Black Stone',
      category: 'stone',
      baseColor: '#2b2c2a',
      pbr: { roughness: 0.4, metallic: 0, textureSetRef: 'stone_kadappa', repeatScale: 900 },
      styleTags: ['chettinad-heritage'],
    },
    furnitureFamilies: ['burma-teak', 'carved-pillar', 'brass-detail'],
    lightingNotes: 'Warm 2700K, brass hanging lamps, deep verandah shade and pillared light pools.',
    textileNotes: 'Chettinad cotton checks, turmeric and maroon silks, kalamkari panels.',
    decorElements: ['brass kuthuvilakku', 'carved teak pillars', 'Tanjore painting', 'pidi vilakku sconces'],
    budgetTier: 'premium',
    reasoning:
      'Glossy hand-made Athangudi tile and Burma teak are the irreducible Chettinad signatures; eggplant and turmeric carry the Chettiar drama.',
    roomOverrides: {
      bathroom: {
        floorMaterial: {
          name: 'Kadappa Black Stone',
          category: 'stone',
          baseColor: '#2b2c2a',
          pbr: { roughness: 0.4, metallic: 0, textureSetRef: 'stone_kadappa', repeatScale: 900 },
          styleTags: ['chettinad-heritage'],
        },
      },
    },
  },
  {
    id: 'modern-farmhouse',
    name: 'Modern Farmhouse',
    description:
      'Relaxed rustic-contemporary — shiplap whites, warm woods, matte black, soft greens and creams.',
    palette: ['#f6f2e9', '#3c3a36', '#9aa284', '#b9986a', '#d8cdb6'],
    wallPaint: {
      name: 'Farmhouse White',
      category: 'paint',
      baseColor: '#f6f2e9',
      pbr: { roughness: 0.94, metallic: 0, repeatScale: 1000 },
      styleTags: ['modern-farmhouse'],
    },
    accentWall: {
      name: 'Sage Green',
      category: 'paint',
      baseColor: '#9aa284',
      pbr: { roughness: 0.92, metallic: 0, repeatScale: 1000 },
      styleTags: ['modern-farmhouse'],
    },
    floorMaterial: {
      name: 'Wide-Plank Oak',
      category: 'wood',
      baseColor: '#b9986a',
      pbr: { roughness: 0.62, metallic: 0, textureSetRef: 'wood_floor_oak', repeatScale: 1500 },
      styleTags: ['modern-farmhouse'],
    },
    wetFloorMaterial: {
      name: 'Matte Hex Tile',
      category: 'ceramicTile',
      baseColor: '#d8cdb6',
      pbr: { roughness: 0.5, metallic: 0, textureSetRef: 'tiles_hex_matte', repeatScale: 450 },
      styleTags: ['modern-farmhouse'],
    },
    furnitureFamilies: ['shaker-wood', 'matte-black-metal', 'slipcover-linen'],
    lightingNotes: 'Warm 2700K, matte-black barn pendants, exposed Edison-style bulbs over the island.',
    textileNotes: 'Washed linen, ticking stripes, chunky knit throws, jute layered rugs.',
    decorElements: ['black-framed glass', 'enamelware', 'dried-stem bunches', 'butcher-block surfaces'],
    budgetTier: 'moderate',
    reasoning:
      'White shiplap-feel walls, wide oak planks and matte-black metal are the farmhouse trio; sage keeps it current, not country-kitsch.',
    roomOverrides: {
      bathroom: {
        floorMaterial: {
          name: 'Matte Hex Tile',
          category: 'ceramicTile',
          baseColor: '#d8cdb6',
          pbr: { roughness: 0.5, metallic: 0, textureSetRef: 'tiles_hex_matte', repeatScale: 450 },
          styleTags: ['modern-farmhouse'],
        },
      },
    },
  },
  {
    id: 'scandinavian-light',
    name: 'Scandinavian Light',
    description:
      'Nordic brightness — chalky whites, blonde ash, pale grey-blue, hygge wool and bare light.',
    palette: ['#f8f6f1', '#d8c9a8', '#aeb8bf', '#7e756a', '#c9b79c'],
    wallPaint: {
      name: 'Chalk White',
      category: 'paint',
      baseColor: '#f8f6f1',
      pbr: { roughness: 0.95, metallic: 0, repeatScale: 1000 },
      styleTags: ['scandinavian-light'],
    },
    accentWall: {
      name: 'Pale Nordic Blue',
      category: 'paint',
      baseColor: '#aeb8bf',
      pbr: { roughness: 0.93, metallic: 0, repeatScale: 1000 },
      styleTags: ['scandinavian-light'],
    },
    floorMaterial: {
      name: 'Blonde Ash',
      category: 'wood',
      baseColor: '#d8c9a8',
      pbr: { roughness: 0.58, metallic: 0, textureSetRef: 'wood_floor_ash', repeatScale: 1500 },
      styleTags: ['scandinavian-light'],
    },
    wetFloorMaterial: {
      name: 'White Matte Porcelain',
      category: 'ceramicTile',
      baseColor: '#eceae4',
      pbr: { roughness: 0.4, metallic: 0, textureSetRef: 'tiles_porcelain', repeatScale: 600 },
      styleTags: ['scandinavian-light'],
    },
    furnitureFamilies: ['blonde-wood', 'soft-curves', 'wool-upholstery'],
    lightingNotes: 'Neutral 3000K, paper globe pendants, candle clusters, maximise daylight with sheer panels.',
    textileNotes: 'Undyed wool, chunky knits, sheepskin throws, sheer linen, subtle tonal stripes.',
    decorElements: ['sheepskin layer', 'pale-wood stools', 'simple ceramics', 'leafy single stems'],
    budgetTier: 'budget',
    reasoning:
      'Chalky white plus blonde ash plus one cool grey-blue is the maximum-light Nordic recipe; wool and sheepskin add hygge warmth.',
  },
  {
    id: 'mid-century-modern',
    name: 'Mid-century Modern',
    description:
      'Retro-clean 1950s warmth — walnut, mustard and teal, tapered legs, organic geometry.',
    palette: ['#ece3d2', '#7a4a2b', '#d39a2d', '#2f6e6a', '#c4502f'],
    wallPaint: {
      name: 'Warm Plaster White',
      category: 'paint',
      baseColor: '#ece3d2',
      pbr: { roughness: 0.93, metallic: 0, repeatScale: 1000 },
      styleTags: ['mid-century-modern'],
    },
    accentWall: {
      name: 'Teal Statement',
      category: 'paint',
      baseColor: '#2f6e6a',
      pbr: { roughness: 0.9, metallic: 0, repeatScale: 1000 },
      styleTags: ['mid-century-modern'],
    },
    floorMaterial: {
      name: 'Walnut Plank',
      category: 'wood',
      baseColor: '#7a4a2b',
      pbr: { roughness: 0.5, metallic: 0, textureSetRef: 'wood_floor_walnut', repeatScale: 1400 },
      styleTags: ['mid-century-modern'],
    },
    wetFloorMaterial: {
      name: 'Penny Round Tile',
      category: 'ceramicTile',
      baseColor: '#d3c2a0',
      pbr: { roughness: 0.32, metallic: 0, textureSetRef: 'tiles_penny', repeatScale: 350 },
      styleTags: ['mid-century-modern'],
    },
    furnitureFamilies: ['walnut-taper-leg', 'molded-shell', 'tweed-upholstery'],
    lightingNotes: 'Warm 2700K, sputnik/globe fixtures, arc floor lamp, brass and opal-glass accents.',
    textileNotes: 'Mustard and teal wool tweed, geometric prints, low-pile shag rug accents.',
    decorElements: ['starburst clock', 'ceramic bud vases', 'abstract geometric art', 'rubber plant'],
    budgetTier: 'moderate',
    reasoning:
      'Walnut with mustard and teal on tapered organic forms is the unmistakable mid-century formula; warm plaster keeps it inviting.',
  },
  {
    id: 'monochrome-luxe',
    name: 'Monochrome Luxe',
    description:
      'Tonal black-and-white drama — charcoal, ivory, polished concrete, blackened metal, marble veins.',
    palette: ['#f2f0ec', '#9a958d', '#3a3a38', '#1c1c1a', '#c8c3ba'],
    wallPaint: {
      name: 'Soft Ivory',
      category: 'paint',
      baseColor: '#f2f0ec',
      pbr: { roughness: 0.9, metallic: 0, repeatScale: 1000 },
      styleTags: ['monochrome-luxe'],
    },
    accentWall: {
      name: 'Charcoal Microcement',
      category: 'concrete',
      baseColor: '#3a3a38',
      pbr: { roughness: 0.55, metallic: 0, textureSetRef: 'concrete_microcement', repeatScale: 1600 },
      styleTags: ['monochrome-luxe'],
    },
    floorMaterial: {
      name: 'Carrara-Tone Marble',
      category: 'marble',
      baseColor: '#e7e5e0',
      pbr: { roughness: 0.16, metallic: 0, textureSetRef: 'marble_carrara', repeatScale: 1400 },
      styleTags: ['monochrome-luxe'],
    },
    wetFloorMaterial: {
      name: 'Honed Black Granite',
      category: 'granite',
      baseColor: '#1c1c1a',
      pbr: { roughness: 0.35, metallic: 0, textureSetRef: 'granite_black', repeatScale: 900 },
      styleTags: ['monochrome-luxe'],
    },
    furnitureFamilies: ['blackened-steel', 'boucle-curves', 'lacquer-veneer'],
    lightingNotes: 'Neutral 3000K, linear architectural fixtures, hidden cove grazing, single sculptural statement lamp.',
    textileNotes: 'Ivory boucle, charcoal velvet, tonal grey wool rugs, zero colour — texture carries it.',
    decorElements: ['monochrome large-format art', 'matte black objets', 'smoked-glass vessels', 'sculptural ceramics'],
    budgetTier: 'premium',
    reasoning:
      'A strict ivory-to-black ramp with marble against charcoal microcement makes texture and contrast do all the work — gallery-grade restraint.',
    roomOverrides: {
      bathroom: {
        floorMaterial: {
          name: 'Honed Black Granite',
          category: 'granite',
          baseColor: '#1c1c1a',
          pbr: { roughness: 0.35, metallic: 0, textureSetRef: 'granite_black', repeatScale: 900 },
          styleTags: ['monochrome-luxe'],
        },
      },
    },
  },
];

export function getStylePack(id: string): StylePack {
  const pack = STYLE_PACKS.find((p) => p.id === id);
  if (!pack) throw new Error(`unknown style pack "${id}"`);
  return pack;
}
